"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-30 07:15:07.797067
"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('career_dimensions',
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('career_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ntype', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ntype', 'name')
    )
    op.create_index(op.f('ix_career_nodes_ntype'), 'career_nodes', ['ntype'], unique=False)
    op.create_table('exams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('full_name', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('subjects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('board', sa.String(length=60), nullable=False),
    sa.Column('class_level', sa.String(length=40), nullable=False),
    sa.Column('stream', sa.String(length=60), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('icon', sa.String(length=60), nullable=False),
    sa.Column('tone', sa.String(length=20), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('published_version', sa.Integer(), nullable=False),
    sa.Column('has_draft', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('board', 'class_level', 'stream', 'name')
    )
    op.create_index(op.f('ix_subjects_board'), 'subjects', ['board'], unique=False)
    op.create_index(op.f('ix_subjects_class_level'), 'subjects', ['class_level'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('activity_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('ref_id', sa.UUID(), nullable=True),
    sa.Column('module', sa.String(length=20), nullable=False),
    sa.Column('minutes', sa.Float(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_events_created_at'), 'activity_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_events_kind'), 'activity_events', ['kind'], unique=False)
    op.create_index(op.f('ix_activity_events_ref_id'), 'activity_events', ['ref_id'], unique=False)
    op.create_index(op.f('ix_activity_events_user_id'), 'activity_events', ['user_id'], unique=False)
    op.create_table('admin_invites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_admin_invites_email'), 'admin_invites', ['email'], unique=False)
    op.create_index(op.f('ix_admin_invites_invited_by'), 'admin_invites', ['invited_by'], unique=False)
    op.create_table('career_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_id', sa.UUID(), nullable=False),
    sa.Column('to_id', sa.UUID(), nullable=False),
    sa.Column('requirement', sa.String(length=20), nullable=True),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['career_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_id'], ['career_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_id', 'to_id')
    )
    op.create_index(op.f('ix_career_edges_from_id'), 'career_edges', ['from_id'], unique=False)
    op.create_index(op.f('ix_career_edges_to_id'), 'career_edges', ['to_id'], unique=False)
    op.create_table('chapters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapters_subject_id'), 'chapters', ['subject_id'], unique=False)
    op.create_table('content_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_tasks_created_by'), 'content_tasks', ['created_by'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('lang', sa.String(length=10), nullable=False),
    sa.Column('source_only', sa.Boolean(), nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('curriculum_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculum_versions_created_by'), 'curriculum_versions', ['created_by'], unique=False)
    op.create_index(op.f('ix_curriculum_versions_subject_id'), 'curriculum_versions', ['subject_id'], unique=False)
    op.create_table('daily_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('meta', sa.String(length=300), nullable=False),
    sa.Column('dur_min', sa.Integer(), nullable=False),
    sa.Column('why', sa.String(length=80), nullable=False),
    sa.Column('tone', sa.String(length=10), nullable=False),
    sa.Column('link', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_tasks_day'), 'daily_tasks', ['day'], unique=False)
    op.create_index(op.f('ix_daily_tasks_user_id'), 'daily_tasks', ['user_id'], unique=False)
    op.create_table('eval_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('expected_answer', sa.Text(), nullable=False),
    sa.Column('expected_locations', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('off_material', sa.Boolean(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_cases_created_by'), 'eval_cases', ['created_by'], unique=False)
    op.create_index(op.f('ix_eval_cases_subject_id'), 'eval_cases', ['subject_id'], unique=False)
    op.create_table('eval_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('framework', sa.String(length=20), nullable=False),
    sa.Column('pipeline_version', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('failures', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('question_bank', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('simulation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_eval_runs_created_by'), 'eval_runs', ['created_by'], unique=False)
    op.create_table('exam_facts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_facts_exam_id'), 'exam_facts', ['exam_id'], unique=False)
    op.create_table('exam_subjects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_subjects_exam_id'), 'exam_subjects', ['exam_id'], unique=False)
    op.create_table('privacy_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('user_label', sa.String(length=320), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_path', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_privacy_requests_resolved_by'), 'privacy_requests', ['resolved_by'], unique=False)
    op.create_index(op.f('ix_privacy_requests_user_id'), 'privacy_requests', ['user_id'], unique=False)
    op.create_table('quizzes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('difficulty_mode', sa.String(length=20), nullable=False),
    sa.Column('types', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('topic_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('time_limit_s', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quizzes_user_id'), 'quizzes', ['user_id'], unique=False)
    op.create_table('saved_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('ref_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=400), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'kind', 'ref_id')
    )
    op.create_index(op.f('ix_saved_items_user_id'), 'saved_items', ['user_id'], unique=False)
    op.create_table('search_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('query', sa.String(length=300), nullable=False),
    sa.Column('normalized', sa.String(length=300), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_logs_created_at'), 'search_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_search_logs_normalized'), 'search_logs', ['normalized'], unique=False)
    op.create_index(op.f('ix_search_logs_user_id'), 'search_logs', ['user_id'], unique=False)
    op.create_table('student_exam_plans',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('target_session', sa.String(length=60), nullable=False),
    sa.Column('hours_per_week', sa.Integer(), nullable=False),
    sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'exam_id')
    )
    op.create_table('student_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('nickname', sa.String(length=80), nullable=False),
    sa.Column('school', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('avatar', sa.Integer(), nullable=False),
    sa.Column('board', sa.String(length=60), nullable=False),
    sa.Column('class_level', sa.String(length=40), nullable=False),
    sa.Column('stream', sa.String(length=60), nullable=True),
    sa.Column('languages', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('subject_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('interests', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('goals', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('exam_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('diag_mode', sa.String(length=20), nullable=False),
    sa.Column('prefs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('career_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('onboarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('exam_units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exam_subject_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_subject_id'], ['exam_subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_units_exam_subject_id'), 'exam_units', ['exam_subject_id'], unique=False)
    op.create_table('kb_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('mime', sa.String(length=120), nullable=False),
    sa.Column('size_label', sa.String(length=80), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('chapter_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_sources_chapter_id'), 'kb_sources', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_kb_sources_created_by'), 'kb_sources', ['created_by'], unique=False)
    op.create_index(op.f('ix_kb_sources_owner_id'), 'kb_sources', ['owner_id'], unique=False)
    op.create_index(op.f('ix_kb_sources_status'), 'kb_sources', ['status'], unique=False)
    op.create_index(op.f('ix_kb_sources_subject_id'), 'kb_sources', ['subject_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=12), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('lang', sa.String(length=10), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('support', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('platform', sa.String(length=60), nullable=False),
    sa.Column('rtype', sa.String(length=40), nullable=False),
    sa.Column('creator', sa.String(length=200), nullable=False),
    sa.Column('duration_label', sa.String(length=80), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=1000), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('class_level', sa.String(length=40), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('chapter_id', sa.UUID(), nullable=True),
    sa.Column('languages', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('difficulty', sa.String(length=40), nullable=False),
    sa.Column('quality', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_ok', sa.Boolean(), nullable=True),
    sa.Column('signal', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_resources_chapter_id'), 'resources', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_resources_created_by'), 'resources', ['created_by'], unique=False)
    op.create_index(op.f('ix_resources_status'), 'resources', ['status'], unique=False)
    op.create_index(op.f('ix_resources_subject_id'), 'resources', ['subject_id'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chapter_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('est_minutes', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_chapter_id'), 'topics', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_topics_slug'), 'topics', ['slug'], unique=False)
    op.create_table('content_units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('slide', sa.Integer(), nullable=True),
    sa.Column('t_start', sa.Float(), nullable=True),
    sa.Column('t_end', sa.Float(), nullable=True),
    sa.Column('heading', sa.String(length=300), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('concepts', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('prereq_topic_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('labels', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('image_path', sa.String(length=1000), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['kb_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_units_source_id'), 'content_units', ['source_id'], unique=False)
    op.create_index(op.f('ix_content_units_topic_id'), 'content_units', ['topic_id'], unique=False)
    op.create_table('exam_topics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('prereq_id', sa.UUID(), nullable=True),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prereq_id'], ['exam_topics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_id'], ['exam_units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_topics_prereq_id'), 'exam_topics', ['prereq_id'], unique=False)
    op.create_index(op.f('ix_exam_topics_topic_id'), 'exam_topics', ['topic_id'], unique=False)
    op.create_index(op.f('ix_exam_topics_unit_id'), 'exam_topics', ['unit_id'], unique=False)
    op.create_table('mastery',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('p', sa.Float(), nullable=False),
    sa.Column('uncertainty', sa.Float(), nullable=False),
    sa.Column('n_obs', sa.Integer(), nullable=False),
    sa.Column('last_evidence', sa.String(length=200), nullable=False),
    sa.Column('last_evidence_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fsrs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'topic_id')
    )
    op.create_index(op.f('ix_mastery_next_review_at'), 'mastery', ['next_review_at'], unique=False)
    op.create_table('mastery_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('correct', sa.Float(), nullable=False),
    sa.Column('p_before', sa.Float(), nullable=False),
    sa.Column('p_after', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mastery_events_topic_id'), 'mastery_events', ['topic_id'], unique=False)
    op.create_index(op.f('ix_mastery_events_user_id'), 'mastery_events', ['user_id'], unique=False)
    op.create_table('resource_feedback',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('helpful', sa.String(length=8), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'resource_id')
    )
    op.create_table('resource_progress',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'resource_id')
    )
    op.create_table('resource_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(length=120), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_reports_resource_id'), 'resource_reports', ['resource_id'], unique=False)
    op.create_index(op.f('ix_resource_reports_user_id'), 'resource_reports', ['user_id'], unique=False)
    op.create_table('resource_topics',
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resource_id', 'topic_id')
    )
    op.create_table('study_materials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('input_kind', sa.String(length=20), nullable=False),
    sa.Column('source_label', sa.String(length=1000), nullable=False),
    sa.Column('subject_label', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('outputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('favorite', sa.Boolean(), nullable=False),
    sa.Column('disabled_by', sa.UUID(), nullable=True),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['disabled_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['kb_sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_materials_disabled_by'), 'study_materials', ['disabled_by'], unique=False)
    op.create_index(op.f('ix_study_materials_source_id'), 'study_materials', ['source_id'], unique=False)
    op.create_index(op.f('ix_study_materials_status'), 'study_materials', ['status'], unique=False)
    op.create_index(op.f('ix_study_materials_user_id'), 'study_materials', ['user_id'], unique=False)
    op.create_table('topic_prereqs',
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('prereq_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['prereq_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('topic_id', 'prereq_id')
    )
    op.create_table('topic_progress',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'topic_id')
    )
    op.create_table('content_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['study_materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_flags_material_id'), 'content_flags', ['material_id'], unique=False)
    op.create_index(op.f('ix_content_flags_user_id'), 'content_flags', ['user_id'], unique=False)
    op.create_table('exam_topic_resources',
    sa.Column('exam_topic_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['exam_topic_id'], ['exam_topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('exam_topic_id', 'resource_id')
    )
    op.create_table('flashcards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('front', sa.Text(), nullable=False),
    sa.Column('back', sa.Text(), nullable=False),
    sa.Column('topic_label', sa.String(length=200), nullable=False),
    sa.Column('source_loc', sa.String(length=120), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['study_materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['content_units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flashcards_material_id'), 'flashcards', ['material_id'], unique=False)
    op.create_index(op.f('ix_flashcards_unit_id'), 'flashcards', ['unit_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('qtype', sa.String(length=20), nullable=False),
    sa.Column('difficulty', sa.String(length=10), nullable=False),
    sa.Column('stem', sa.Text(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('answer_num', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('tolerance', sa.Float(), nullable=False),
    sa.Column('rubric', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('misconceptions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('verification', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('irt_b', sa.Float(), nullable=False),
    sa.Column('times_served', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['content_units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_status'), 'questions', ['status'], unique=False)
    op.create_index(op.f('ix_questions_topic_id'), 'questions', ['topic_id'], unique=False)
    op.create_index(op.f('ix_questions_unit_id'), 'questions', ['unit_id'], unique=False)
    op.create_table('student_exam_topics',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exam_topic_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_topic_id'], ['exam_topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'exam_topic_id')
    )
    op.create_table('card_states',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('flashcard_id', sa.UUID(), nullable=False),
    sa.Column('fsrs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_rating', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['flashcard_id'], ['flashcards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'flashcard_id')
    )
    op.create_index(op.f('ix_card_states_due_at'), 'card_states', ['due_at'], unique=False)
    op.create_table('quiz_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quiz_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('grade', sa.String(length=10), nullable=True),
    sa.Column('rubric_hits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('misconception', sa.Text(), nullable=False),
    sa.Column('mastery_before', sa.Float(), nullable=True),
    sa.Column('mastery_after', sa.Float(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_items_question_id'), 'quiz_items', ['question_id'], unique=False)
    op.create_index(op.f('ix_quiz_items_quiz_id'), 'quiz_items', ['quiz_id'], unique=False)
    # ### end Alembic commands ###
    op.execute('CREATE INDEX IF NOT EXISTS ix_content_units_embedding ON content_units USING hnsw (embedding vector_cosine_ops)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_questions_embedding ON questions USING hnsw (embedding vector_cosine_ops)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_content_units_text_trgm ON content_units USING gin (text gin_trgm_ops)')



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_items_quiz_id'), table_name='quiz_items')
    op.drop_index(op.f('ix_quiz_items_question_id'), table_name='quiz_items')
    op.drop_table('quiz_items')
    op.drop_index(op.f('ix_card_states_due_at'), table_name='card_states')
    op.drop_table('card_states')
    op.drop_table('student_exam_topics')
    op.drop_index(op.f('ix_questions_unit_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_topic_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_status'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_flashcards_unit_id'), table_name='flashcards')
    op.drop_index(op.f('ix_flashcards_material_id'), table_name='flashcards')
    op.drop_table('flashcards')
    op.drop_table('exam_topic_resources')
    op.drop_index(op.f('ix_content_flags_user_id'), table_name='content_flags')
    op.drop_index(op.f('ix_content_flags_material_id'), table_name='content_flags')
    op.drop_table('content_flags')
    op.drop_table('topic_progress')
    op.drop_table('topic_prereqs')
    op.drop_index(op.f('ix_study_materials_user_id'), table_name='study_materials')
    op.drop_index(op.f('ix_study_materials_status'), table_name='study_materials')
    op.drop_index(op.f('ix_study_materials_source_id'), table_name='study_materials')
    op.drop_index(op.f('ix_study_materials_disabled_by'), table_name='study_materials')
    op.drop_table('study_materials')
    op.drop_table('resource_topics')
    op.drop_index(op.f('ix_resource_reports_user_id'), table_name='resource_reports')
    op.drop_index(op.f('ix_resource_reports_resource_id'), table_name='resource_reports')
    op.drop_table('resource_reports')
    op.drop_table('resource_progress')
    op.drop_table('resource_feedback')
    op.drop_index(op.f('ix_mastery_events_user_id'), table_name='mastery_events')
    op.drop_index(op.f('ix_mastery_events_topic_id'), table_name='mastery_events')
    op.drop_table('mastery_events')
    op.drop_index(op.f('ix_mastery_next_review_at'), table_name='mastery')
    op.drop_table('mastery')
    op.drop_index(op.f('ix_exam_topics_unit_id'), table_name='exam_topics')
    op.drop_index(op.f('ix_exam_topics_topic_id'), table_name='exam_topics')
    op.drop_index(op.f('ix_exam_topics_prereq_id'), table_name='exam_topics')
    op.drop_table('exam_topics')
    op.drop_index(op.f('ix_content_units_topic_id'), table_name='content_units')
    op.drop_index(op.f('ix_content_units_source_id'), table_name='content_units')
    op.drop_table('content_units')
    op.drop_index(op.f('ix_topics_slug'), table_name='topics')
    op.drop_index(op.f('ix_topics_chapter_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_resources_subject_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_status'), table_name='resources')
    op.drop_index(op.f('ix_resources_created_by'), table_name='resources')
    op.drop_index(op.f('ix_resources_chapter_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_kb_sources_subject_id'), table_name='kb_sources')
    op.drop_index(op.f('ix_kb_sources_status'), table_name='kb_sources')
    op.drop_index(op.f('ix_kb_sources_owner_id'), table_name='kb_sources')
    op.drop_index(op.f('ix_kb_sources_created_by'), table_name='kb_sources')
    op.drop_index(op.f('ix_kb_sources_chapter_id'), table_name='kb_sources')
    op.drop_table('kb_sources')
    op.drop_index(op.f('ix_exam_units_exam_subject_id'), table_name='exam_units')
    op.drop_table('exam_units')
    op.drop_table('student_profiles')
    op.drop_table('student_exam_plans')
    op.drop_index(op.f('ix_search_logs_user_id'), table_name='search_logs')
    op.drop_index(op.f('ix_search_logs_normalized'), table_name='search_logs')
    op.drop_index(op.f('ix_search_logs_created_at'), table_name='search_logs')
    op.drop_table('search_logs')
    op.drop_index(op.f('ix_saved_items_user_id'), table_name='saved_items')
    op.drop_table('saved_items')
    op.drop_index(op.f('ix_quizzes_user_id'), table_name='quizzes')
    op.drop_table('quizzes')
    op.drop_index(op.f('ix_privacy_requests_user_id'), table_name='privacy_requests')
    op.drop_index(op.f('ix_privacy_requests_resolved_by'), table_name='privacy_requests')
    op.drop_table('privacy_requests')
    op.drop_index(op.f('ix_exam_subjects_exam_id'), table_name='exam_subjects')
    op.drop_table('exam_subjects')
    op.drop_index(op.f('ix_exam_facts_exam_id'), table_name='exam_facts')
    op.drop_table('exam_facts')
    op.drop_index(op.f('ix_eval_runs_created_by'), table_name='eval_runs')
    op.drop_table('eval_runs')
    op.drop_index(op.f('ix_eval_cases_subject_id'), table_name='eval_cases')
    op.drop_index(op.f('ix_eval_cases_created_by'), table_name='eval_cases')
    op.drop_table('eval_cases')
    op.drop_index(op.f('ix_daily_tasks_user_id'), table_name='daily_tasks')
    op.drop_index(op.f('ix_daily_tasks_day'), table_name='daily_tasks')
    op.drop_table('daily_tasks')
    op.drop_index(op.f('ix_curriculum_versions_subject_id'), table_name='curriculum_versions')
    op.drop_index(op.f('ix_curriculum_versions_created_by'), table_name='curriculum_versions')
    op.drop_table('curriculum_versions')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_content_tasks_created_by'), table_name='content_tasks')
    op.drop_table('content_tasks')
    op.drop_index(op.f('ix_chapters_subject_id'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_career_edges_to_id'), table_name='career_edges')
    op.drop_index(op.f('ix_career_edges_from_id'), table_name='career_edges')
    op.drop_table('career_edges')
    op.drop_index(op.f('ix_admin_invites_invited_by'), table_name='admin_invites')
    op.drop_index(op.f('ix_admin_invites_email'), table_name='admin_invites')
    op.drop_table('admin_invites')
    op.drop_index(op.f('ix_activity_events_user_id'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_ref_id'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_kind'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_created_at'), table_name='activity_events')
    op.drop_table('activity_events')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subjects_class_level'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_board'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_table('exams')
    op.drop_index(op.f('ix_career_nodes_ntype'), table_name='career_nodes')
    op.drop_table('career_nodes')
    op.drop_table('career_dimensions')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
